### ISSUE TITLE
Capturing a profile causes the GPU fans to spin at full speed until reboot/gpu reset

### ISSUE THREAD

**Issue by mahkoh** [GPUOpen-Tools/radeon_developer_panel#12]
After setting

```bash
sudo chmod ugo+w /sys/class/drm/card0/device/power_dpm_force_performance_level
```

and capturing a profile in RadeonDeveloperPanel, the GPU fans start to spin at full speed and do not return to normal even after RadeonDeveloperPanel has been closed.

I was able to recover from this by either restarting the PC or executing

```bash
cat /sys/kernel/debug/dri/0/amdgpu_gpu_recover
```

I'm running the 5.14.8 kernel on Arch Linux with a Radeon RX 570.

**Comment by mguerret-amd** [comment]
@mahkoh Which driver are you running?

**Comment by mguerret-amd** [comment]
@mahkoh Thanks for your report, however I am unable to reproduce this issue with 
**Linux Kernel: 5.14.9-arch2-1**
**Driver: vulkan-amdgpu-pro 21.30_1290604-1**

I'd like to add that Arch Linux is not an officially supported platform by AMD. Please upgrade to a newer kernel release if possible and see if this fixes your issue.

**Comment by mahkoh** [comment]
This problem happened again today and I noticed that RadeonDeveloperPanel sets `/sys/class/hwmon/hwmon3/pwm1_enable` to 1 and sometimes fails to reset it to 2. Manually resetting it to 2 fixes the problem.
