### ISSUE TITLE
Application does not go online

### ISSUE THREAD

**Issue by bok11** [GPUOpen-Tools/radeon_developer_panel#13]
I have a linux platform with a  Ryzen V1000 with integrated graphics (gfx902).
As far as i can tell this is supported for openCL.

I have an opencl application called GPUFullThrottle, following this documentation: https://radeon-developer-panel.readthedocs.io/en/latest/

I have added the application with the name: GPUFullThrottle and api: Auto
Upon launching my application it is still offline and never comes online.

Everything is launched as root.

**Comment by bok11** [comment]
I looked again at the requirements, and see opencl only lists support for windows OS.
As direct X is windows only, is it correctly understood i am limited to profiling vulkan application on linux?

**Comment by MattGuerrette** [comment]
@bok11 Yes, Vulkan is currently the only supported API on Linux
