### ISSUE TITLE
v1.13.1 Radeon Developer Panel crashed!

### ISSUE THREAD

**Issue by kaiserschmarrn0** [GPUOpen-Tools/radeon_developer_panel#24]
[log.txt](https://github.com/GPUOpen-Tools/radeon_developer_panel/files/10147728/log.txt)

**Comment by kaiserschmarrn0** [comment]
i should mention this happens immediately when running the executable

**Comment by kaiserschmarrn0** [comment]
also, i can't upload the core dump on github. lmk if should email that somewhere.

**Comment by mguerret-amd** [comment]
This should be resolved by the latest RDP v2.8 release.
