### ISSUE TITLE
setup.sh assumes AMD GPU as /dev/dri/card0

### ISSUE THREAD

**Issue by stolk** [GPUOpen-Tools/radeon_developer_panel#30]
The script located here:
```
RadeonDeveloperToolSuite-2023-04-25-1075/scripts/setup.sh
```
...assumes that the AMD GPU is the only GPU in the system, as it hard-codes `drm/card0` in this command:
```
sudo chmod ugo+w /sys/class/drm/card0/device/power_dpm_force_performance_level
```
If there is an Intel iGPU in the system as well, the AMD GPU could be `card1` instead of `card0`.

**Comment by stolk** [comment]
This is still broken in the december release.

Both the 'who' usage and the card0/card1.

This is a little better:
```
# Change ownership of amd_rmv tracing directory and all subdirectories to current user
current_user=$(who | awk '{print $1}' | head -1)
sudo chown $current_user -R /sys/kernel/tracing/instances/amd_rmv
```

Just add ` | head -1` to the command.

**Comment by mguerret-amd** [comment]
This should be fixed in latest releases of RDTS
