### ISSUE TITLE
Radeon Developer Mode on screen text

### ISSUE THREAD

**Issue by WoodyPWX** [GPUOpen-Tools/radeon_developer_panel#32]
Hello there,
could anyone please help me to disable this RDM text, visible everywhere?
![image](https://user-images.githubusercontent.com/8375403/186957179-5f625c32-2965-4105-924c-7fc362d67115.png)
Thank you,
Tomas

**Comment by siliconvoodoo** [comment]
This overlay makes using blender difficult. And there is no RadeonDeveloperService.exe task on the system.
this hud activates itself detecting that the TdrDelay key in the registry is not standard 2 seconds. It's a pain

**Comment by MattGuerrette** [comment]
> This overlay makes using blender difficult. And there is no RadeonDeveloperService.exe task on the system. this hud activates itself detecting that the TdrDelay key in the registry is not standard 2 seconds. It's a pain

As mentioned above, are you running RenderDoc with RGP Interop enabled? The only way that overlay should appear is through one of the following:

1. Running **RadeonDeveloperPanel.exe**
2. Running **RadeonDeveloperService.exe** or **RadeonDeveloperServiceCLI.exe**
3. Running RenderDoc with **Radeon GPU Profiler integration** enabled in settings

Please check to make sure none of these are currently active on your system.

**Comment by siliconvoodoo** [comment]
I don't use RenderDoc, but I use pix, and indeed closing it removed the overlay. It also caused blender to crash while it was running; that happened. But yes globally you are right it was the influence of a debug tool.

**Comment by MattGuerrette** [comment]
@siliconvoodoo Yes, PIX is a fourth case which enables developer mode. Glad you were able to resolve that.

**Comment by WoodyPWX** [comment]
I got back to profiling using RDTS 2024/09/26 1411 and the debug text EVERYWHERE is still super annoying! Come on guys! How hard could it be to let us disable it? 

![image](https://github.com/user-attachments/assets/e94d30a6-3370-4e73-a1cd-d027b6eeb8d7)

**Comment by MattGuerrette** [comment]
@WoodyPWX I would recommend adding Unity to the blocklist and publishing your Unity application (.exe) and running that separately for profiling.

**Comment by WoodyPWX** [comment]
Our Unity game is DX11 only and that is limiting our options for GPU profiling. We can't add D3D12 shaders to the build for memory reasons, so my workaround is to profile GPU directly in the editor by forcing D3D12 there. Poor CPU performance shouldn't be a problem for GPU captures. But the debug messages over every render texture is a big annoyance.
