### ISSUE TITLE
Fail to capture FlaxEngine profile on Ubuntu 22.04 and Windows 10

### ISSUE THREAD

**Issue by B5paper** [GPUOpen-Tools/radeon_developer_panel#49]
FlaxEditor uses vulkan as a rendering backend on Ubuntu. I started `RadeonDeveloperPanel` with connection ready. When I ran FlaxEditor, the tab of RDP didn't be switched automatically. And there were no new executable app shown in the app list.

I repeated same operations on Windows 10, and the result is the same as above.

`uname -a`: 
`Linux hUbuntu-2204 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

Type of AMD GPU card: Radeon RX 6500 XT (RADV NAVI24)

Driver version: installed by `amgpu-install`

**Comment by mguerret-amd** [comment]
@B5paper I am not able to reproduce this issue. FlaxEditor runs fine for me on Ubuntu 24.04 and I am able to capture RGP profiles using RDP
