### ISSUE TITLE
[3.1] Failed to Start on Linux

### ISSUE THREAD

**Issue by Snowiiii** [GPUOpen-Tools/radeon_developer_panel#52]
Hello, 3.1 just released and i got excited to test it out.

While i had not problems with older versions, Starting with this version i get this error:
`./RadeonDeveloperPanel: error while loading shared libraries: libicudata.so.70: cannot open shared object file: No such file or directory

I not 100% is im using 3.1, The Folder name is `RadeonDeveloperToolSuite-2024-06-26-1341`. And on the Download website its still 3.0
![image](https://github.com/GPUOpen-Tools/radeon_developer_panel/assets/71594357/ede3ed99-6ed0-4948-b533-f2e500e760fe)
But the blog says i should download it from there https://gpuopen.com/learn/rdts-migrates-to-qt-6/

**Comment by chesik-amd** [comment]
Thanks for the report. I will ask the RDP team to take a look. In the meantime, it looks like the required library is part of the package in the "lib" sub-directory, so the following command should work:

LD_LIBRARY_PATH=./lib ./RadeonDeveloperPanel

Also, the link you mentioned was updated, but the server cache was not properly cleared for that page. I pinged the gpuopen.com admins and they cleared the cache. The live page should be correct now.

**Comment by Snowiiii** [comment]
> Thanks for the report. I will ask the RDP team to take a look. In the meantime, it looks like the required library is part of the package in the "lib" sub-directory, so the following command should work:
> 
> LD_LIBRARY_PATH=./lib ./RadeonDeveloperPanel
> 
> Out of curiosity, which Linux distribution are you running on?
> 
> Also, the link you mentioned was updated, but the server cache was not properly cleared for that page. I pinged the gpuopen.com admins and they cleared the cache. The live page should be correct now.

Hey, Thanks for the quick response. Im currently using Manjaro (Kernel 6.9) with Mesa 24

I installed the required lib libicudata version 70 from Source because its not in the core repo anymore. You should proberbly update to the latest icu version 75, Its available for most distros and is often preinstalled i think

**Comment by chesik-amd** [comment]
This should be fixed in the new Radeon Developer Tool Suite that was published yesterday
