### ISSUE TITLE
GCN support - Driver Experiments.

### ISSUE THREAD

**Issue by GreenShadows** [GPUOpen-Tools/radeon_developer_panel#56]
Most AMD GPUs on the market are still GCN (polaris and Vega), AMD still sells vega-based APUs by the way, so I don't understand why limit a useful debugging tool to RDNA!?

**Comment by GreenShadows** [comment]
Then... they don't know why Nvidia's software is always praised and they eat up more and more marketshare... what a terrible attitude.

**Comment by bpurnomo** [comment]
Hi,
  Unfortunately, AMD has moved GCN support for Adrenalin driver to legacy products.  No new features are added to the legacy products.
Please see https://community.amd.com/t5/gaming/product-and-os-support-update-for-radeon-software-adrenalin-21-6/ba-p/477423
