### ISSUE TITLE
Application keeps going offline seconds after it is found

### ISSUE THREAD

**Issue by mdabbs** [GPUOpen-Tools/radeon_developer_panel#6]
I'm running the Radeon Developer Panel in the hopes of profiling my opencl application.  The panel, connects and I'm on the system page.  I then run my app and it shows up briefly in the list, along with a PID, then the PID goes away about a second later and the app says its offline.

The computer is running Windows 10, with the 20.12.1 AMD drivers. I only have an RX570 in the machine.

Is the fact that its multi-threaded a problem? Or is the 570 too old?

And and all help would be appreciated.

**Comment by bpurnomo** [comment]
RX570 is not supported for RGP OpenCL.
See the list of supported hardware for OpenCL in https://github.com/GPUOpen-Tools/radeon_gpu_profiler#supported-rdna-and-gcn-hardware-1

**Comment by mdabbs** [comment]
Does the RX 570 not fall under the "AMD Radeon RX 400, RX 500 series"?

Supported RDNA and GCN hardware
AMD Radeon RX 6000 series
AMD Radeon RX 5000 series
AMD Radeon VII
AMD RX Vega 64 and RX Vega 56
AMD Ryzen™ Processors with Radeon Vega Graphics
AMD Radeon R9 Fury and Nano series
AMD Radeon RX 400, RX 500 series
AMD Tonga R9 285, R9 380
